podman: use HELPER_BINARIES_DIR env instead of inreplace to set location of libexec
PR podman#13372 started recognizing a new environment variable $HELPER_BINARIES_DIR
that can be used to set location of helper binaries such as `gvproxy`. We can set
this variable during the build instead of using an `inreplace` to update the
location inside the Go source code.

This is a follow up to PR #93794 which added the `inreplace`.

Tested: `brew reinstall -s podman` and confirmed that `podman machine start` works
as expected. If I only remove the `inreplace` without setting the environment variable,
then `podman machine start` fails with:

  Error: unable to start host networking: "could not find \"gvproxy\" in one of [...]"

Where the list of paths doesn't include the libexec of this keg.