boxes 2.0.0
* Update boxes.rb for version 2.0.0
* Update license
  In response to `brew audit --strict`:
  ```console
  ❯ brew audit --strict boxes
  boxes:
  * Formula boxes contains deprecated SPDX licenses: ["GPL-2.0"].
  You may need to add `-only` or `-or-later` for GNU licenses (e.g. `GPL`, `LGPL`, `AGPL`, `GFDL`).
  For a list of valid licenses check: https://spdx.org/licenses/
  Error: 1 problem in 1 formula detected
  ```
  and [verified by author](https://github.com/ascii-boxes/boxes/issues/77#issuecomment-811896990)
* Fix whitespace
* It's actually pcre2

Closes #74350.

Signed-off-by: Carlo Cabrera <30379873+carlocab@users.noreply.github.com>
Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>