questdb: rebuild
QuestDB: fix source sha256 hash

The 6.2.1 formula has a wrong hash. As a result it fails when used
with `--build-from-source` flag. This PR fixes this. This is the failure:
```
==> Verifying checksum for '18f7f06c5dab0d85cf10c021b9f930aa99d06d801ebc9224b14d1764064af591--questdb-6.2.1-no-jre-bin.tar.gz'
Error: questdb: SHA256 mismatch
Expected: 607d95346841846e015e6723af25b4047dc1acdf1912d0a259ffff15c314b93e
  Actual: 4c7411c5585c4a2d39994a28004dd0f2fa3fba2c8c42d01a8ac3777e1bcca02e
```

The change also introduces inreplace to fix the installation
prefix to match the homebrew layout.

Closes #98593.

Signed-off-by: Sean Molenaar <1484494+SMillerDev@users.noreply.github.com>
Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>