watch 3.3.11
Build from the tag directly, using Autotools so that we can apply as a
patch an upstream commit that happens to fix
  "error: conflicting types for 'user_from_uid'"

Building from git turned up a bug with linking to libintl, so set
-lintl in LDFLAGS to work around that.

Closes #2167.

Signed-off-by: ilovezfs <ilovezfs@icloud.com>