x86-64-elf-binutils: Bump revision
It'd be good bump revision in the previous commit but test would fail
otherwise:

 brew test roolebo/core/x86_64-elf-binutils
 Testing roolebo/core/x86_64-elf-binutils
 ==> /usr/local/Cellar/x86_64-elf-binutils/2.34_1/bin/x86_64-elf-as --64 -o test-s.o test-s.s
 ==> /usr/local/Cellar/x86_64-elf-binutils/2.34/bin/x86_64-elf-objdump -a test-s.o
 Error: roolebo/core/x86_64-elf-binutils: failed
 An exception occurred within a child process:
   Errno::ENOENT: No such file or directory - /usr/local/Cellar/x86_64-elf-binutils/2.34/bin/x86_64-elf-objdump
 /usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in ``'
 /usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:11:in `shell_output'
 /usr/local/Homebrew/Library/Taps/roolebo/homebrew-core/Formula/x86_64-elf-binutils.rb:38:in `block in <class:X8664ElfBinutils>'
 /usr/local/Homebrew/Library/Homebrew/formula.rb:1821:in `block (3 levels) in run_test'
 /usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
 /usr/local/Homebrew/Library/Homebrew/formula.rb:1820:in `block (2 levels) in run_test'
 /usr/local/Homebrew/Library/Homebrew/formula.rb:888:in `with_logging'
 /usr/local/Homebrew/Library/Homebrew/formula.rb:1819:in `block in run_test'
 /usr/local/Homebrew/Library/Homebrew/formula.rb:2063:in `block in mktemp'
 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
 /usr/local/Homebrew/Library/Homebrew/formula.rb:2062:in `mktemp'
 /usr/local/Homebrew/Library/Homebrew/formula.rb:1813:in `run_test'
 /usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
 /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
 /usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'

The test doesn't fail on revision bump if "#{bin}" is used as path
prefix to objdump instead of "#{Formula["x86_64-elf-binutils"].bin}":

 brew test Formula/x86_64-elf-binutils.rb
 Testing roolebo/core/x86_64-elf-binutils
 ==> /usr/local/Cellar/x86_64-elf-binutils/2.34_1/bin/x86_64-elf-as --64 -o test-s.o test-s.s
 ==> /usr/local/Cellar/x86_64-elf-binutils/2.34_1/bin/x86_64-elf-objdump -a test-s.o