glib: fix inreplace (#52369)
Fails with
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
/usr/local/Cellar/glib/2.64.1_1/lib/pkgconfig/glib-2.0.pc:
  expected replacement of "Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include" with "Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include -I/usr/local/opt/gettext/include"

This is due to the latest meson update (0.54.0)